#ifndef __CAPTUREEVENTS
#define __CAPTUREEVENTS 1

typedef enum e_CaptureEvents
{

  DEFAULT,
  MODULE_NOT_FOUND,
  INVALID_INTEFACE,
  ASSIGN_DATATYPE_MISMATCH,
  USELESS_STATEMENT,
  UNDEFINED_VARIABLE,
  INVALID_TOKEN,
  UNDEFINED_METHOD,
  INVALID_RETURN_TYPE

} CaptureEvents;

#endif