#ifndef __CAPTUREEVENTS
#define __CAPTUREEVENTS 1

typedef enum e_CaptureEvents
{

  DEFAULT,
  MODULE_NOT_FOUND,
  INVALID_INTEFACE,
  ASSIGN_DATATYPE_MISMATCH,
  USELESS_STATEMENT,
  INVALID_TOKEN

} CaptureEvents;

#endif